mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\close_other.py" "E:\work\git\sublime_setting_sync\sublime_setting\close_other.py"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Default (Windows).sublime-keymap" "E:\work\git\sublime_setting_sync\sublime_setting\Default (Windows).sublime-keymap"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Flake8Lint.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Flake8Lint.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Function Name Display.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Function Name Display.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\lua.sublime-completions" "E:\work\git\sublime_setting_sync\sublime_setting\lua.sublime-completions"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\lua_local_require.sublime-snippet" "E:\work\git\sublime_setting_sync\sublime_setting\lua_local_require.sublime-snippet"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\mklink_cmd_for_debug.bat" "E:\work\git\sublime_setting_sync\sublime_setting\mklink_cmd_for_debug.bat"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\mylocal_lua.sublime-snippet" "E:\work\git\sublime_setting_sync\sublime_setting\mylocal_lua.sublime-snippet"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Package Control.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\SublimeLinter.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\SublimeLinter.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Terminal.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Terminal.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\test.sublime-snippet" "E:\work\git\sublime_setting_sync\sublime_setting\test.sublime-snippet"
