mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\close_other.py" "E:\work\git\sublime_setting_sync\sublime_setting\close_other.py"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Default (Windows).sublime-keymap" "E:\work\git\sublime_setting_sync\sublime_setting\Default (Windows).sublime-keymap"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\mklink_cmd_for_debug.bat" "E:\work\git\sublime_setting_sync\sublime_setting\mklink_cmd_for_debug.bat"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Package Control.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Package Control.sublime-settings"
mklink "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\Preferences.sublime-settings" "E:\work\git\sublime_setting_sync\sublime_setting\Preferences.sublime-settings"
